add k8s v1.26.9 release
rancher/kubernetes pull request #109
Opened 2023-09-15 07:12 UTC by chiukapoor

**What this PR does / why we need it**:
- add k8s v1.26.9 release

**Which issue(s) this PR fixes** 
- Fixes https://github.com/rancher/rancher/issues/42812

2023-09-18 21:18 UTC, jiaqiluo requested changes
~Have one comment, otherwise LGTM~

Update: LGTM.

2023-09-18 21:18 UTC, jiaqiluo commented on Dockerfile.dapper
> +FROM registry.suse.com/bci/golang:1.19
Can we bump the tag to `1.20` to match the upstream's?

2023-09-18 21:20 UTC, jiaqiluo approved these changes

2023-09-18 21:22 UTC, jiaqiluo approved these changes

2023-09-19 02:52 UTC, snasovich approved these changes

2023-09-19 17:18 UTC, merged